---
version: "2.1"
services:
  ViSiON-2:
    image: vision2bbsres:v1.0
    container_name: v2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - drive_g:/dos/drive_g
    ports:
      - '23:23'
      - '5901:5901'
    restart: unless-stopped